/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'
import { Route as AuthenticatedMoonRouteImport } from './routes/_authenticated/moon'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as ApiTtsRouteImport } from './routes/api/tts'
import { Route as AuthenticatedPlayerIdRouteImport } from './routes/_authenticated/player.$id'
import { Route as AuthenticatedRecordIdRouteImport } from './routes/_authenticated/record.$id'

const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/_authenticated/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/_authenticated/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMoonRoute = AuthenticatedMoonRouteImport.update({
  id: '/_authenticated/moon',
  path: '/moon',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/_authenticated/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPlayerIdRoute = AuthenticatedPlayerIdRouteImport.update({
  id: '/_authenticated/player/$id',
  path: '/player/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRecordIdRoute = AuthenticatedRecordIdRouteImport.update({
  id: '/_authenticated/record/$id',
  path: '/record/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/home': typeof AuthenticatedHomeRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/moon': typeof AuthenticatedMoonRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/api/tts': typeof ApiTtsRoute
  '/player/$id': typeof AuthenticatedPlayerIdRoute
  '/record/$id': typeof AuthenticatedRecordIdRoute
}
export interface FileRoutesByTo {
  '/home': typeof AuthenticatedHomeRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/moon': typeof AuthenticatedMoonRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/api/tts': typeof ApiTtsRoute
  '/player/$id': typeof AuthenticatedPlayerIdRoute
  '/record/$id': typeof AuthenticatedRecordIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/library': typeof AuthenticatedLibraryRoute
  '/_authenticated/moon': typeof AuthenticatedMoonRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/api/tts': typeof ApiTtsRoute
  '/_authenticated/player/$id': typeof AuthenticatedPlayerIdRoute
  '/_authenticated/record/$id': typeof AuthenticatedRecordIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/home'
    | '/library'
    | '/moon'
    | '/profile'
    | '/api/tts'
    | '/player/$id'
    | '/record/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/home'
    | '/library'
    | '/moon'
    | '/profile'
    | '/api/tts'
    | '/player/$id'
    | '/record/$id'
  id:
    | '__root__'
    | '/_authenticated/home'
    | '/_authenticated/library'
    | '/_authenticated/moon'
    | '/_authenticated/profile'
    | '/api/tts'
    | '/_authenticated/player/$id'
    | '/_authenticated/record/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRoute
  AuthenticatedMoonRoute: typeof AuthenticatedMoonRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  ApiTtsRoute: typeof ApiTtsRoute
  AuthenticatedPlayerIdRoute: typeof AuthenticatedPlayerIdRoute
  AuthenticatedRecordIdRoute: typeof AuthenticatedRecordIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/moon': {
      id: '/_authenticated/moon'
      path: '/moon'
      fullPath: '/moon'
      preLoaderRoute: typeof AuthenticatedMoonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/player/$id': {
      id: '/_authenticated/player/$id'
      path: '/player/$id'
      fullPath: '/player/$id'
      preLoaderRoute: typeof AuthenticatedPlayerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/record/$id': {
      id: '/_authenticated/record/$id'
      path: '/record/$id'
      fullPath: '/record/$id'
      preLoaderRoute: typeof AuthenticatedRecordIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedLibraryRoute: AuthenticatedLibraryRoute,
  AuthenticatedMoonRoute: AuthenticatedMoonRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  ApiTtsRoute: ApiTtsRoute,
  AuthenticatedPlayerIdRoute: AuthenticatedPlayerIdRoute,
  AuthenticatedRecordIdRoute: AuthenticatedRecordIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
